# Set prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# --- Key Bindings ---

# Intuitive window-splitting keys
bind ] split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

# Fix for Ctrl+L (Clear Screen)
# Now use: <Prefix> + <Ctrl+L> to clear the screen
bind C-l send-keys 'C-l'

# Reload config file with <prefix> + r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config Reloaded!"

# --- General Settings ---
set -g base-index 1              # Start windows at 1
setw -g pane-base-index 1        # Start panes at 1
set -g mouse on                  # Enable mouse
set -g default-terminal "screen-256color"

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator' # Handles Ctrl-h/j/k/l automatically

# Minimal Status Config
set -g @minimal-tmux-fg '#000000'
set -g @minimal-tmux-bg '#698DDA'
set -g @minimal-tmux-indicator-str ' TMUX '
set -g @minimal-tmux-indicator true

# Initialize TPM (Keep at bottom)
run '~/.config/tmux/plugins/tpm/tpm'
